### ISSUE TITLE
No Data Collected

### ISSUE THREAD

**Issue by ogmios2** [nikharris0/probemon#16]
Hello, 

I was hoping that someone could point me into right direction. 

I am getting this error and nothing is being collected.

`Traceback (most recent call last):
  File "probemon.py", line 96, in <module>
    main()
  File "probemon.py", line 93, in main
    sniff(iface=args.interface, prn=built_packet_cb, store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 926, in sniff
    p = s.recv()
  File "/usr/local/lib/python2.7/dist-packages/scapy/supersocket.py", line 55, in recv
    cls, val, ts = self.recv_raw(x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 517, in recv_raw
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down
`

I am on a raspberry pi 3 B running Kali. The network card does show as running in monitor mode when using `iwconfig`

Thanks for anyone's time!

**Comment by gregory-whaley** [comment]
I am running a VM with Kali as the OS.  Everything installs and runs without error except there are no packets detected.  The log file is opened but has zero bytes.  airodump-ng shows packets detected just fine.  Any debug ideas?

**Comment by ogmios2** [comment]
Gregory. It looks like this isn't supported anymore. I decided to go with another script called probequest. It seems similar. I may also just use Kismet and have someone help work on a log viewer for it.

**Comment by gregory-whaley** [comment]
Thanks for the great reply!  I’ll look more into probequest.

**Comment by cloventt** [comment]
I had a similar issue while running `probemon` on MacOS 10.14. 

The solution I found was changing the script to call `sniff()` with `monitor=True`. This put my wireless interface into monitor mode and allowed packets to be collected.
