### ISSUE TITLE
Error on RPi

### ISSUE THREAD

**Issue by ram1505** [nikharris0/probemon#2]
Hi,
I'm getting the following error when I try to run the python file.

`Traceback (most recent call last):
  File "probemon.py", line 96, in <module>
    main()
  File "probemon.py", line 87, in main
    handler = RotatingFileHandler(args.output, maxBytes=args.max_bytes, backupCount=args.max_backups)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 21] Is a directory: '/home/pi/scapy_test'`

**Comment by nikharris0** [comment]
This is likely because you gave it a directory path. Try giving it
/home/pi/scapy_test/probemon.log

**Comment by ram1505** [comment]
Works perfectly when I change to probemon.log. Thanks.
