### ISSUE TITLE
ImportError: cannot import name singledispatch

### ISSUE THREAD

**Issue by beankeeper** [nikharris0/probemon#21]
**by starting probemon.py, i got this message:**

**/probemon# python probemon.py -i mon0 --mac-info --ssid --log**
Traceback (most recent call last):
  File "probemon.py", line 10, in <module>
    import netaddr
  File "/usr/local/lib/python2.7/dist-packages/netaddr-0.8.0-py2.7.egg/netaddr/__init__.py", line 18, in <module>
    from netaddr.core import (AddrConversionError, AddrFormatError,
  File "/usr/local/lib/python2.7/dist-packages/netaddr-0.8.0-py2.7.egg/netaddr/core.py", line 11, in <module>
    from netaddr.compat import _callable, _iter_dict_keys
  File "/usr/local/lib/python2.7/dist-packages/netaddr-0.8.0-py2.7.egg/netaddr/compat.py", line 93, in <module>
    import importlib_resources as _importlib_resources
  File "/usr/local/lib/python2.7/dist-packages/importlib_resources-0.0.0-py2.7.egg/importlib_resources/__init__.py", line 3, in <module>
    from ._common import (
  File "/usr/local/lib/python2.7/dist-packages/importlib_resources-0.0.0-py2.7.egg/importlib_resources/_common.py", line 7, in <module>
    from functools import singledispatch
ImportError: cannot import name singledispatch

**How can i solve this ?**

**Comment by ninoCan** [comment]
This is an old thread, I am answering just for future reader's sake. 

It seems that you're using python 2.7
https://docs.python.org/2.7/library/functools.html#module-functools
Functools module wasn't yet supporting `singledispatch` for that version of python
