### ISSUE TITLE
UnicodeDecodeError in logger.info(delimiter.join(fields))

### ISSUE THREAD

**Issue by LaurentLacheny** [nikharris0/probemon#5]
I have this exception : 
_Traceback (most recent call last):
  File "probemon.py", line 94, in <module>
    main()
  File "probemon.py", line 91, in main
    sniff(iface=args.interface, prn=built_packet_cb, store=0)
  File "/home/llacheny/.local/lib/python2.7/site-packages/scapy/sendrecv.py", line 620, in sniff
    r = prn(p)
  File "probemon.py", line 57, in packet_callback
    logger.info(delimiter.join(fields))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb6 in position 28: ordinal not in range(128)_

It occurs with SSIDs using non ascii characters. 
The following change corrects the issue : 
		**logger.info(delimiter.join([f.decode("utf-8") for f in fields]))**

**Comment by AshwinKrishn** [comment]
@LaurentLacheny  You have not enabled the monitor mode to your wifi chip. 
if you see this

$iwconfig wlan0 -> "mode : managed"

run these

$sudo ifconfig wlan0 down
$sudo iwconfig wlan0 mode monitor
$sudo ifconfig wlan0 up
Optional 👍  if you run $iwconfig wlan0 you will see "mode : monitor"
now run the program.
