### ISSUE TITLE
Iso timestamp gives type object 'datetime.datetime' has no attribute 'datetime'

### ISSUE THREAD

**Issue by Dmeowmixer** [nikharris0/probemon#7]
$ sudo python probemon.py -i wlan0 -t iso -o probemon.log -f -s -r
Traceback (most recent call last):
  File "probemon.py", line 96, in <module>
    main()
  File "probemon.py", line 93, in main
    sniff(iface=args.interface, prn=built_packet_cb, store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 620, in sniff
    r = prn(p)
  File "probemon.py", line 36, in packet_callback
    log_time = datetime.datetime.now().isoformat()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

unix working fine, not sure if this is a local problem.

**Comment by prylypko** [comment]
I have same error on Kali

**Comment by prylypko** [comment]
@Dmeowmixer this fixes the problem https://github.com/nikharris0/probemon/pull/3/commits/c4920dbda3469f1c67c10f1e548886d78e87f3d1

**Comment by mflannery** [comment]
On line 36 remove the second datetime:

log_time = datetime.now().isoformat()

This works but the date and time is messed up.

**Comment by pawmendi** [comment]
The following line 36:

`log_time = datetime.fromtimestamp(int(time.time())).strftime('%Y-%m-%d %H:%M:%S')`

works with the correct date and time.
